#ifndef CONSTANTES_DEFINE_HEADER
#define CONSTANTES_DEFINE_HEADER


#define NOMBRE_MIN_QUESTION 2
#define NOMBRE_MAX_QUESTION 5
#define NOMBRE_OPERATIONS 4
#define VALEUR_MIN_OPERANDE 1
#define VALEUR_MAX_OPERANDE 200

#define PORT_SERVEUR 12345
#define NOMBRE_MAX_CONNEXION_CLIENT 100


#endif
